# Here you can specify default options for TinyMCE across all controllers
#
 theme: advanced
 plugins:
  - table
  - fullscreen
  - paste
 theme_advanced_buttons3: "pastetext,pasteword,selectall"
 paste_remove_styles_if_webkit: false
 paste_retain_style_properties: "*"
